 alias  ds="sudo kubectl describe "
 alias  g="sudo kubectl get --all-namespaces --v=6 -o wide"
 alias  a="sudo kubectl apply --v=6"
 alias  kd="sudo kubectl delete "
 alias  r="sudo kubectl replace --v=8"
 alias  k="sudo kubectl"
 alias  ka="sudo kubeadm"


 alias  d="sudo docker"
 alias  l="sudo docker logs"
 alias  rmi="sudo docker rmi"
 alias  dps="sudo docker ps -a"

 alias  gs="git status"
 alias  gp="git pull"
 alias  gb="git branch"
 alias  ga="git add"
 alias  gc="git commit"
 alias  gd="git diff"
 alias  gdc="git diff --cached"
