apiVersion: v1
kind: Service
metadata:
  name: trade-gateway-service
spec:
  selector:
    app: trade-gateway
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 12231
    targetPort: 12231
    nodePort: 30006
