apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: gateway-container
        image: registry:5000/gaoliang.gateway:latest    
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8000
