apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: user 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: registry:5000/gaoliang.user.server
        ports:
        - containerPort: 8081
