apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    name: user-service
spec:
  type: NodePort
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
    name: http
    nodePort: 30002
  selector:
    app: gaoliang-user
